(source gnu)
(source melpa)

(package-file "~/.cask/cask.el")

;; cask
(depends-on "flycheck-cask")            ; flycheck for cask projects
(depends-on "flycheck-color-mode-line")

;; c
(depends-on "company-c-headers")        ; c/c++ backend for company

;; git
(depends-on "git-gutter")

;; haskell
(depends-on "flycheck-haskell")
(depends-on "flymake-haskell-multi")
(depends-on "ghc")
(depends-on "haskell-mode")

;; latex
(depends-on "auctex")
(depends-on "company-auctex")
(depends-on "company-math")
(depends-on "latex-extra")
(depends-on "latex-preview-pane")
(depends-on "latex-pretty-symbols")

;; lua
(depends-on "company-lua")
(depends-on "flymake-lua")
(depends-on "lua-mode")

;; markdown
(depends-on "markdown-mode")
(depends-on "gh-md")

;; ocaml
(depends-on "tuareg")

;; org-mode
(depends-on "org")

;; python
(depends-on "flycheck-pyflakes")
(depends-on "company-jedi")
(depends-on "jedi-core")

;; Others
(depends-on "column-enforce-mode")      ; enforce 80 column rules
(depends-on "company")                  ; completion engine
(depends-on "crosshairs")               ; highlight current line
(depends-on "flx-ido")                  ; fuzzy matching integration
(depends-on "highlight-chars")          ; highlight set of characters
(depends-on "highlight-indent-guides")  ; highlight indentation
(depends-on "neotree")                  ; folder tree
(depends-on "powerline")                ; powerline for emacs
(depends-on "rainbow-delimiters")       ; display parenthesis with ccolors
(depends-on "smartparens")              ; insert automatically parenthesis
(depends-on "yasnippet")                ; snippets

