(source gnu)
(source melpa)

(package-file "~/.cask/cask.el")

(depends-on "company")
(depends-on "company-c-headers")
(depends-on "fill-column-indicator")
(depends-on "flycheck-cask")
(depends-on "flycheck-color-mode-line")
(depends-on "flx-ido")
(depends-on "monokai-theme")
(depends-on "neotree")
(depends-on "powerline")
(depends-on "smartparens")
(depends-on "tuareg")
(depends-on "yasnippet")
(depends-on "whitespace")
(depends-on "flycheck-tip")

;; Docker
(depends-on "dockerfile-mode")


;; Scala
(depends-on "scala-mode2")
(depends-on "ensime")


;; latex
(depends-on "latex-preview-pane")
(depends-on "auctex-latexmk")
(depends-on "company-math")
(depends-on "latex-extra")
(depends-on "latex-pretty-symbols")


;; git
(depends-on "git-gutter")
(depends-on "magit")


;; lua
(depends-on "company-lua")
(depends-on "flymake-lua")
(depends-on "lua-mode")


;; python
(depends-on "flycheck-pyflakes")
(depends-on "company-jedi")
(depends-on "jedi-core")


;; plot
(depends-on "gnuplot-mode")

;; org-mode
(depends-on "org")

(depends-on "markdown-mode")
(depends-on "gh-md")